global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rizzerve-auth-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:8080']
    scrape_timeout: 10s

  - job_name: 'rizzerve-auth-jvm'
    metrics_path: '/actuator/metrics'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:8080']