name: Continuous Integration (CI)

on:
  push:
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4

      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Set gradlew executable
        run: chmod +x ./gradlew

      - name: Set environment variables for JWT
        run: |
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> $GITHUB_ENV

      - name: Create jwt.properties file
        run: |
          echo "jwt.secret.key=${{ secrets.JWT_SECRET_KEY }}" > src/main/resources/jwt.properties
          echo "jwt.expiration=${{ secrets.JWT_EXPIRATION }}" >> src/main/resources/jwt.properties

      - name: Run unit tests
        run: ./gradlew test
